import matplotlib.pyplot as plt
from control.matlab import *
import control as ctr


TimeLine = []
for i in range(0,3000):
    TimeLine.append(i)

def n_w(num, den):
    w = tf(num, den)
    return w


bz_z = n_w(num=[3], den=[1])
print('Передаточная функция Безынерционного звена: \n %s' % bz_z)
y, x = ctr.step_response(bz_z,TimeLine)
plt.plot(x, y, "b")
plt.title('Переходная функция Безынерционного звена')
plt.ylabel('Амплитудное значение')
plt.xlabel('Время')
plt.grid(True)
plt.show()
y, x = ctr.impulse_response(bz_z,TimeLine)
plt.plot(x, y, "r")
plt.title('Импульсная функция Безынерционное звено')
plt.ylabel('Амплитудное значение')
plt.xlabel('Время')
plt.grid(True)
plt.show()
mag, phase, omega = bode(bz_z, dB=True)
plt.title('ЛАЧХ и ЛАФЧХ апериодического звена')
plt.plot()
plt.show()

ap_z = n_w(num=5, den=[3, 1])
print('Передаточная функция апериодического звена: \n %s' % ap_z)
y, x = step(ap_z)
plt.plot(x, y, "b")
plt.title('Переходная функция апериодического звена')
plt.ylabel('Амплитудное значение')
plt.xlabel('Время')
plt.grid(True)
plt.show()
y, x = impulse(ap_z)
plt.plot(x, y, "r")
plt.title('Импульсная функция апериодического звена')
plt.ylabel('Амплитудное значение')
plt.xlabel('Время')
plt.grid(True)
plt.show()
mag, phase, omega = bode(ap_z, dB=True)
plt.title('ЛАЧХ и ЛАФЧХ апериодического звена')
plt.plot()
plt.show()

in_z = n_w(num=3, den=[1, 0])
print('Передаточная функция интегрирующего звена: \n %s' % in_z)
y, x = step(in_z)
plt.plot(x, y, "b")
plt.title('Переходная функция интегрирующего звена')
plt.ylabel('Амплитудное значение')
plt.xlabel('Время')
plt.grid(True)
plt.show()
y, x = impulse(in_z)
plt.plot(x, y, "r")
plt.title('Импульсная функция интегрирующего звена')
plt.ylabel('Амплитудное значение')
plt.xlabel('Время')
plt.grid(True)
plt.show()
mag, phase, omega = bode(in_z, dB=True)
plt.title('ЛАЧХ и ЛАФЧХ интегрирующего звена')
plt.plot()
plt.show()

rD_z = n_w(num=[1, 0], den=[4, 1])
print('Передаточная функция реального дифференциирующего звена: \n %s' % rD_z)
y, x = step(rD_z)
plt.plot(x, y, "b")
plt.title('Переходная функция реального дифференциирующего звена')
plt.ylabel('Амплитудное значение')
plt.xlabel('Время')
plt.grid(True)
plt.show()
y, x = impulse(rD_z)
plt.plot(x, y, "r")
plt.title('Импульсная функция реального дифференциирующего звена')
plt.ylabel('Амплитудное значение')
plt.xlabel('Время')
plt.grid(True)
plt.show()
mag, phase, omega = bode(rD_z, dB=True)
plt.title('ЛАЧХ и ЛАФЧХ реального дифференциирующего звена')
plt.plot()
plt.show()
